package com.mark.vote.model;

import java.io.Serializable;
import java.util.Date;

public class VoteItem extends VoteItemKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    private Integer voteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    private Integer voteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.vote_desc
     *
     * @return the value of t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public Integer getVoteDesc() {
        return voteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public VoteItem withVoteDesc(Integer voteDesc) {
        this.setVoteDesc(voteDesc);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.vote_desc
     *
     * @param voteDesc the value for t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public void setVoteDesc(Integer voteDesc) {
        this.voteDesc = voteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.vote_num
     *
     * @return the value of t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public Integer getVoteNum() {
        return voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public VoteItem withVoteNum(Integer voteNum) {
        this.setVoteNum(voteNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.vote_num
     *
     * @param voteNum the value for t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public void setVoteNum(Integer voteNum) {
        this.voteNum = voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.create_time
     *
     * @return the value of t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public VoteItem withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.create_time
     *
     * @param createTime the value for t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.update_time
     *
     * @return the value of t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public VoteItem withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.update_time
     *
     * @param updateTime the value for t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", voteDesc=").append(voteDesc);
        sb.append(", voteNum=").append(voteNum);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}