package com.mark.vote.model;

import java.io.Serializable;
import java.util.Date;

public class VoteTheme implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.user_id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.title
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.status
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.vote_max
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Integer voteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.vote_min
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Integer voteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.close_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.create_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.update_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_theme.description
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.id
     *
     * @return the value of t_vote_theme.id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.id
     *
     * @param id the value for t_vote_theme.id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.user_id
     *
     * @return the value of t_vote_theme.user_id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.user_id
     *
     * @param userId the value for t_vote_theme.user_id
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.title
     *
     * @return the value of t_vote_theme.title
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.title
     *
     * @param title the value for t_vote_theme.title
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.status
     *
     * @return the value of t_vote_theme.status
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.status
     *
     * @param status the value for t_vote_theme.status
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.vote_max
     *
     * @return the value of t_vote_theme.vote_max
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Integer getVoteMax() {
        return voteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withVoteMax(Integer voteMax) {
        this.setVoteMax(voteMax);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.vote_max
     *
     * @param voteMax the value for t_vote_theme.vote_max
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setVoteMax(Integer voteMax) {
        this.voteMax = voteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.vote_min
     *
     * @return the value of t_vote_theme.vote_min
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Integer getVoteMin() {
        return voteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withVoteMin(Integer voteMin) {
        this.setVoteMin(voteMin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.vote_min
     *
     * @param voteMin the value for t_vote_theme.vote_min
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setVoteMin(Integer voteMin) {
        this.voteMin = voteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.close_time
     *
     * @return the value of t_vote_theme.close_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withCloseTime(Date closeTime) {
        this.setCloseTime(closeTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.close_time
     *
     * @param closeTime the value for t_vote_theme.close_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.create_time
     *
     * @return the value of t_vote_theme.create_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.create_time
     *
     * @param createTime the value for t_vote_theme.create_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.update_time
     *
     * @return the value of t_vote_theme.update_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.update_time
     *
     * @param updateTime the value for t_vote_theme.update_time
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_theme.description
     *
     * @return the value of t_vote_theme.description
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public VoteTheme withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_theme.description
     *
     * @param description the value for t_vote_theme.description
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Tue May 07 23:08:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", voteMax=").append(voteMax);
        sb.append(", voteMin=").append(voteMin);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}