package com.mark.vote.model;

import java.io.Serializable;
import java.util.Date;

public class VoteLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.user_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.vote_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer voteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.vote_item_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer voteItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.vote_num
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer voteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.anoymouse
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Integer anoymouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.create_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_log.vote_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private Date voteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.id
     *
     * @return the value of t_vote_log.id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.id
     *
     * @param id the value for t_vote_log.id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.user_id
     *
     * @return the value of t_vote_log.user_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.user_id
     *
     * @param userId the value for t_vote_log.user_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.vote_id
     *
     * @return the value of t_vote_log.vote_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withVoteId(Integer voteId) {
        this.setVoteId(voteId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.vote_id
     *
     * @param voteId the value for t_vote_log.vote_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.vote_item_id
     *
     * @return the value of t_vote_log.vote_item_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getVoteItemId() {
        return voteItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withVoteItemId(Integer voteItemId) {
        this.setVoteItemId(voteItemId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.vote_item_id
     *
     * @param voteItemId the value for t_vote_log.vote_item_id
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setVoteItemId(Integer voteItemId) {
        this.voteItemId = voteItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.vote_num
     *
     * @return the value of t_vote_log.vote_num
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getVoteNum() {
        return voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withVoteNum(Integer voteNum) {
        this.setVoteNum(voteNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.vote_num
     *
     * @param voteNum the value for t_vote_log.vote_num
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setVoteNum(Integer voteNum) {
        this.voteNum = voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.anoymouse
     *
     * @return the value of t_vote_log.anoymouse
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Integer getAnoymouse() {
        return anoymouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withAnoymouse(Integer anoymouse) {
        this.setAnoymouse(anoymouse);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.anoymouse
     *
     * @param anoymouse the value for t_vote_log.anoymouse
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setAnoymouse(Integer anoymouse) {
        this.anoymouse = anoymouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.create_time
     *
     * @return the value of t_vote_log.create_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.create_time
     *
     * @param createTime the value for t_vote_log.create_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_log.vote_time
     *
     * @return the value of t_vote_log.vote_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public Date getVoteTime() {
        return voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public VoteLog withVoteTime(Date voteTime) {
        this.setVoteTime(voteTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_log.vote_time
     *
     * @param voteTime the value for t_vote_log.vote_time
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    public void setVoteTime(Date voteTime) {
        this.voteTime = voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sun May 05 00:07:04 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", voteId=").append(voteId);
        sb.append(", voteItemId=").append(voteItemId);
        sb.append(", voteNum=").append(voteNum);
        sb.append(", anoymouse=").append(anoymouse);
        sb.append(", createTime=").append(createTime);
        sb.append(", voteTime=").append(voteTime);
        sb.append("]");
        return sb.toString();
    }
}