package com.mark.vote.model;

import java.io.Serializable;
import java.util.Date;

public class VoteItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.title_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer titleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.vote_no
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer voteNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer voteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer voteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.id
     *
     * @return the value of t_vote_item.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.id
     *
     * @param id the value for t_vote_item.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.title_id
     *
     * @return the value of t_vote_item.title_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withTitleId(Integer titleId) {
        this.setTitleId(titleId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.title_id
     *
     * @param titleId the value for t_vote_item.title_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.vote_no
     *
     * @return the value of t_vote_item.vote_no
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getVoteNo() {
        return voteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withVoteNo(Integer voteNo) {
        this.setVoteNo(voteNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.vote_no
     *
     * @param voteNo the value for t_vote_item.vote_no
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setVoteNo(Integer voteNo) {
        this.voteNo = voteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.vote_desc
     *
     * @return the value of t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getVoteDesc() {
        return voteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withVoteDesc(Integer voteDesc) {
        this.setVoteDesc(voteDesc);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.vote_desc
     *
     * @param voteDesc the value for t_vote_item.vote_desc
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setVoteDesc(Integer voteDesc) {
        this.voteDesc = voteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.vote_num
     *
     * @return the value of t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getVoteNum() {
        return voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withVoteNum(Integer voteNum) {
        this.setVoteNum(voteNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.vote_num
     *
     * @param voteNum the value for t_vote_item.vote_num
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setVoteNum(Integer voteNum) {
        this.voteNum = voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.create_time
     *
     * @return the value of t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.create_time
     *
     * @param createTime the value for t_vote_item.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_item.update_time
     *
     * @return the value of t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteItem withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_item.update_time
     *
     * @param updateTime the value for t_vote_item.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_item
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", titleId=").append(titleId);
        sb.append(", voteNo=").append(voteNo);
        sb.append(", voteDesc=").append(voteDesc);
        sb.append(", voteNum=").append(voteNum);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}