package com.mark.vote.model;

import java.io.Serializable;
import java.util.Date;

public class VoteTitle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.theme_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer themeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.type
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.img_name
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.vote_max
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer voteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.vote_min
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer voteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.must_vote
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Integer mustVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_title.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.id
     *
     * @return the value of t_vote_title.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.id
     *
     * @param id the value for t_vote_title.id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.theme_id
     *
     * @return the value of t_vote_title.theme_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withThemeId(Integer themeId) {
        this.setThemeId(themeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.theme_id
     *
     * @param themeId the value for t_vote_title.theme_id
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.title
     *
     * @return the value of t_vote_title.title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.title
     *
     * @param title the value for t_vote_title.title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.type
     *
     * @return the value of t_vote_title.type
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.type
     *
     * @param type the value for t_vote_title.type
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.img_name
     *
     * @return the value of t_vote_title.img_name
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withImgName(Integer imgName) {
        this.setImgName(imgName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.img_name
     *
     * @param imgName the value for t_vote_title.img_name
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setImgName(Integer imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.vote_max
     *
     * @return the value of t_vote_title.vote_max
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getVoteMax() {
        return voteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withVoteMax(Integer voteMax) {
        this.setVoteMax(voteMax);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.vote_max
     *
     * @param voteMax the value for t_vote_title.vote_max
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setVoteMax(Integer voteMax) {
        this.voteMax = voteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.vote_min
     *
     * @return the value of t_vote_title.vote_min
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getVoteMin() {
        return voteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withVoteMin(Integer voteMin) {
        this.setVoteMin(voteMin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.vote_min
     *
     * @param voteMin the value for t_vote_title.vote_min
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setVoteMin(Integer voteMin) {
        this.voteMin = voteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.must_vote
     *
     * @return the value of t_vote_title.must_vote
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Integer getMustVote() {
        return mustVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withMustVote(Integer mustVote) {
        this.setMustVote(mustVote);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.must_vote
     *
     * @param mustVote the value for t_vote_title.must_vote
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setMustVote(Integer mustVote) {
        this.mustVote = mustVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.create_time
     *
     * @return the value of t_vote_title.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.create_time
     *
     * @param createTime the value for t_vote_title.create_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_title.update_time
     *
     * @return the value of t_vote_title.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public VoteTitle withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_title.update_time
     *
     * @param updateTime the value for t_vote_title.update_time
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_title
     *
     * @mbg.generated Sat Jun 29 17:58:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", themeId=").append(themeId);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", imgName=").append(imgName);
        sb.append(", voteMax=").append(voteMax);
        sb.append(", voteMin=").append(voteMin);
        sb.append(", mustVote=").append(mustVote);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}