package com.mark.vote.dao;

import com.mark.vote.model.VoteTheme;
import com.mark.vote.model.VoteThemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface VoteThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    long countByExample(VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int deleteByExample(VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Delete({
        "delete from t_vote_theme",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Insert({
        "insert into t_vote_theme (user_id, title, ",
        "status, vote_max, ",
        "vote_min, close_time, ",
        "create_time, update_time, ",
        "description)",
        "values (#{userId,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{voteMax,jdbcType=INTEGER}, ",
        "#{voteMin,jdbcType=INTEGER}, #{closeTime,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(VoteTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int insertSelective(VoteTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteTheme> selectByExampleWithBLOBsWithRowbounds(VoteThemeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteTheme> selectByExampleWithBLOBs(VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteTheme> selectByExampleWithRowbounds(VoteThemeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteTheme> selectByExample(VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Select({
        "select",
        "id, user_id, title, status, vote_max, vote_min, close_time, create_time, update_time, ",
        "description",
        "from t_vote_theme",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mark.vote.dao.VoteThemeMapper.ResultMapWithBLOBs")
    VoteTheme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") VoteTheme record, @Param("example") VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") VoteTheme record, @Param("example") VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByExample(@Param("record") VoteTheme record, @Param("example") VoteThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByPrimaryKeySelective(VoteTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Update({
        "update t_vote_theme",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "vote_max = #{voteMax,jdbcType=INTEGER},",
          "vote_min = #{voteMin,jdbcType=INTEGER},",
          "close_time = #{closeTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "description = #{description,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(VoteTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_theme
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Update({
        "update t_vote_theme",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "vote_max = #{voteMax,jdbcType=INTEGER},",
          "vote_min = #{voteMin,jdbcType=INTEGER},",
          "close_time = #{closeTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(VoteTheme record);
}