package com.mark.vote.dao;

import com.mark.vote.model.VoteLog;
import com.mark.vote.model.VoteLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface VoteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    long countByExample(VoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int deleteByExample(VoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Delete({
        "delete from t_vote_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Insert({
        "insert into t_vote_log (user_id, vote_id, ",
        "device_id, vote_item_id, ",
        "vote_num, anoymouse, ",
        "create_time, vote_time)",
        "values (#{userId,jdbcType=INTEGER}, #{voteId,jdbcType=INTEGER}, ",
        "#{deviceId,jdbcType=VARCHAR}, #{voteItemId,jdbcType=INTEGER}, ",
        "#{voteNum,jdbcType=INTEGER}, #{anoymouse,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{voteTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int insertSelective(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteLog> selectByExampleWithRowbounds(VoteLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    List<VoteLog> selectByExample(VoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Select({
        "select",
        "id, user_id, vote_id, device_id, vote_item_id, vote_num, anoymouse, create_time, ",
        "vote_time",
        "from t_vote_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mark.vote.dao.VoteLogMapper.BaseResultMap")
    VoteLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") VoteLog record, @Param("example") VoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByExample(@Param("record") VoteLog record, @Param("example") VoteLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    int updateByPrimaryKeySelective(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_log
     *
     * @mbg.generated Sat Jun 08 20:12:30 CST 2019
     */
    @Update({
        "update t_vote_log",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "vote_id = #{voteId,jdbcType=INTEGER},",
          "device_id = #{deviceId,jdbcType=VARCHAR},",
          "vote_item_id = #{voteItemId,jdbcType=INTEGER},",
          "vote_num = #{voteNum,jdbcType=INTEGER},",
          "anoymouse = #{anoymouse,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "vote_time = #{voteTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(VoteLog record);
}